/**
 * Binds the E2E mock engine to the real engine's apply envelope.
 *
 * Why this exists: 30 of 31 E2E specs run against `__ENDSTATE_MOCK_ENGINE__`
 * and none spawns a binary, so the mock is the only engine those specs ever
 * see. It was authored from the GUI's own type definitions rather than from
 * engine output, which meant it emitted `items`/`counts` — fields the apply
 * envelope has never had (`counts` belongs to `capture`, `items` to
 * `generations`). Every E2E spec passed while the GUI's reconciliation was
 * inert in production, because the mock supplied exactly the fields the GUI
 * wrongly expected. A suite that mocks the thing under test verifies only that
 * the consumer agrees with itself.
 *
 * The fixture is generated by `tests/contract.test.js` from a real engine run
 * (see `tests/fixtures/apply-envelope.golden.json`), so this test fails the
 * moment the mock and the producer disagree.
 *
 * It pins SHAPE, not values. Statuses depend on what the host already has
 * installed — a developer machine reports `present`, a clean CI runner reports
 * `to_install` — so asserting values here would make the test host-dependent
 * and it would be silenced rather than fixed.
 */
import { describe, it, expect } from 'vitest';
import golden from '../../tests/fixtures/apply-envelope.golden.json';
import restoreGolden from '../../tests/fixtures/restore-envelope.golden.json';
import inspectionGolden from '../../tests/fixtures/profile-inspect-envelope.golden.json';
import inspectionFixture from '../../e2e/fixtures/profile_inspect.fixture.json';
import { scenarioEnvelope } from './mock-engine';

describe('mock engine conforms to the real profile inspection envelope', () => {
  it('provides the committed long-profile inspection envelope', () => {
    const envelope = scenarioEnvelope('profile_inspect_ok' as never) as Record<string, unknown>;
    expect(envelope).toEqual(inspectionFixture);
  });

  it('keeps the profile inspection wrapper and data shape aligned with the real-engine golden', () => {
    const envelope = inspectionFixture as Record<string, unknown>;
    const data = envelope.data as Record<string, unknown>;
    const goldenData = inspectionGolden.data as Record<string, unknown>;

    for (const key of Object.keys(inspectionGolden).filter((key) => key !== '_generatedBy')) {
      expect(Object.prototype.hasOwnProperty.call(envelope, key), `mock profile envelope is missing ${key}`).toBe(true);
    }
    expect(Object.keys(data).sort()).toEqual(Object.keys(goldenData).sort());
    expect(envelope.schemaVersion).toMatch(/^1\./);
    expect(envelope.command).toBe('profile');
    expect(envelope.success).toBe(true);
    expect(envelope.error).toBeNull();
    expect(data.profile).toEqual(expect.objectContaining({ name: expect.any(String), capturedAt: expect.any(String) }));
    expect(Object.keys((data.apps as Array<Record<string, unknown>>)[0]).sort()).toEqual(
      Object.keys((goldenData.apps as Array<Record<string, unknown>>)[0]).sort(),
    );
    expect(Object.keys((data.settingsApps as Array<Record<string, unknown>>)[0]).sort()).toEqual(
      Object.keys((goldenData.settingsApps as Array<Record<string, unknown>>)[0]).sort(),
    );
  });

  it('preserves the long-profile summary, association matrix, identities, and searchable provenance', () => {
    const data = inspectionFixture.data;
    expect(data.apps).toHaveLength(72);
    expect(data.settingsApps).toHaveLength(8);
    expect(data.summary).toEqual({
      appCount: 72,
      settingsRowCount: 8,
      verifiedSettingsAppCount: 8,
      unidentifiedSettingsRowCount: 0,
    });
    expect(data.apps.filter((app) => app.hasSettings)).toHaveLength(7);
    expect(new Set(data.apps.map((app) => app.id)).size).toBe(data.apps.length);
    for (const app of data.apps) {
      expect(app.id).toBe(`app:${app.manifestAppId.toLowerCase()}:1`);
    }
    expect(data.apps.map((app) => `${app.displayName.toLowerCase()}\u0000${app.id}`)).toEqual(
      [...data.apps]
        .sort((left, right) => {
          const leftKey = `${left.displayName.toLowerCase()}\u0000${left.id}`;
          const rightKey = `${right.displayName.toLowerCase()}\u0000${right.id}`;
          return leftKey < rightKey ? -1 : leftKey > rightKey ? 1 : 0;
        })
        .map((app) => `${app.displayName.toLowerCase()}\u0000${app.id}`),
    );
    expect(data.settingsApps.filter((row) => row.associationStatus === 'included')).toHaveLength(7);
    expect(data.settingsApps.filter((row) => row.associationStatus === 'not_in_profile')).toHaveLength(1);
    for (const row of data.settingsApps.filter((row) => row.associationStatus === 'included')) {
      expect(row.id).toBe(`settings:${row.appId}`);
      expect(row.ownerId).toBe(row.appId);
      expect(row.appIncluded).toBe(true);
      expect(row.candidateAppIds).toEqual([row.appId]);
      expect(row.packageRefs).toEqual(expect.any(Array));
      expect(row.moduleIds).toEqual(expect.any(Array));
    }
    expect(data.settingsApps.find((row) => row.associationStatus === 'not_in_profile')).toMatchObject({
      id: 'settings:package:vendor.absent',
      ownerId: 'package:vendor.absent',
      associationStatus: 'not_in_profile',
      appId: null,
      appIncluded: false,
      candidateAppIds: [],
    });
    expect(data.settingsApps.map((row) => `${row.displayName.toLowerCase()}\u0000${row.id}`)).toEqual(
      [...data.settingsApps]
        .sort((left, right) => {
          const leftKey = `${left.displayName.toLowerCase()}\u0000${left.id}`;
          const rightKey = `${right.displayName.toLowerCase()}\u0000${right.id}`;
          return leftKey < rightKey ? -1 : leftKey > rightKey ? 1 : 0;
        })
        .map((row) => `${row.displayName.toLowerCase()}\u0000${row.id}`),
    );
    expect(data.apps.find((app) => app.manifestAppId === 'cursor')?.packageRefs).toContain('com.endstate.hidden-package-ref');
    expect(data.settingsApps.find((row) => row.appId === 'app:cursor:1')?.moduleIds).toContain('apps.hidden-module-id');
    expect(data.warnings).toContainEqual(expect.objectContaining({ impact: 'inventory_incomplete' }));
  });
});

describe('mock engine conforms to the real apply envelope', () => {
  const envelope = scenarioEnvelope('apply_ok_minimal') as Record<string, unknown>;
  const data = envelope.data as Record<string, unknown>;

  it('emits every data field the real engine emits', () => {
    for (const key of golden.dataKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(data, key),
        `mock apply envelope is missing data.${key}, which the real engine emits`
      ).toBe(true);
    }
  });

  it('emits no data field the real engine does not emit', () => {
    for (const key of golden.forbiddenDataKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(data, key),
        `mock apply envelope emits data.${key}, which belongs to a different command ` +
          `and never appears on an apply envelope — a consumer reading it fails silently`
      ).toBe(false);
    }
  });

  it('emits the real envelope wrapper fields', () => {
    for (const key of golden.envelopeKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(envelope, key),
        `mock envelope is missing ${key}`
      ).toBe(true);
    }
  });

  it('emits actions whose items carry the real action fields', () => {
    const actions = data.actions as Array<Record<string, unknown>>;
    expect(Array.isArray(actions)).toBe(true);
    expect(actions.length).toBeGreaterThan(0);

    // `name` and `driver` matter most: the GUI falls back to the raw package
    // ref when `name` is absent, which is what made a never-installed app show
    // as "Warp.Warp" beside friendly-named rows.
    for (const key of ['id', 'status', 'name', 'driver']) {
      expect(
        Object.prototype.hasOwnProperty.call(actions[0], key),
        `mock action is missing ${key}`
      ).toBe(true);
    }
  });

  it('emits summary with the real aggregate fields', () => {
    const summary = data.summary as Record<string, unknown>;
    for (const key of golden.summaryKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(summary, key),
        `mock summary is missing ${key}`
      ).toBe(true);
    }
  });

  it('emits restoreModulesAvailable entries with entryCount', () => {
    const modules = data.restoreModulesAvailable as Array<Record<string, unknown>>;
    expect(Array.isArray(modules)).toBe(true);
    expect(modules.length).toBeGreaterThan(0);

    for (const key of golden.restoreModuleKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(modules[0], key),
        `mock restoreModulesAvailable entry is missing ${key}`
      ).toBe(true);
    }
  });

  it('exposes dryRun so consumers can distinguish a preview from a real apply', () => {
    expect(typeof data.dryRun).toBe('boolean');
  });
});

/**
 * Binds the mock's restore-bearing scenario to the RESTORE golden
 * (tests/fixtures/restore-envelope.golden.json), regenerated by
 * tests/contract.test.js from a real `apply --enable-restore` run.
 *
 * The apply-golden block above checks restoreModulesAvailable[0] once. This
 * block is stricter on the axis the restore lane exists to protect: EVERY entry
 * must carry every key the real engine emits, and every entryCount must be a
 * positive integer — the engine omits a module with no resolved entries rather
 * than reporting it empty, so membership and count cannot disagree. The mock
 * derives entryCount from a single source list for exactly that reason.
 */
describe('mock engine conforms to the real restore envelope', () => {
  const envelope = scenarioEnvelope('apply_ok_minimal') as Record<string, unknown>;
  const data = envelope.data as Record<string, unknown>;
  const modules = data.restoreModulesAvailable as Array<Record<string, unknown>>;

  it('carries a scoped restoreModulesAvailable list', () => {
    expect(Array.isArray(modules)).toBe(true);
    expect(modules.length).toBeGreaterThan(0);
  });

  it('gives every restore module entry the real engine-authored keys', () => {
    for (const module of modules) {
      for (const key of restoreGolden.restoreModuleKeys) {
        expect(
          Object.prototype.hasOwnProperty.call(module, key),
          `mock restoreModulesAvailable entry ${JSON.stringify(module.id)} is missing ${key}, ` +
            `which the real engine emits`
        ).toBe(true);
      }
    }
  });

  it('reports a positive integer entryCount on every entry (membership cannot disagree with count)', () => {
    for (const module of modules) {
      expect(
        Number.isInteger(module.entryCount) && (module.entryCount as number) > 0,
        `mock restoreModulesAvailable entry ${JSON.stringify(module.id)} has a non-positive ` +
          `or non-integer entryCount ${JSON.stringify(module.entryCount)}`
      ).toBe(true);
    }
  });

  it('emits every data field the real restore envelope emits', () => {
    for (const key of restoreGolden.dataKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(data, key),
        `mock apply envelope is missing data.${key}, which the real restore envelope emits`
      ).toBe(true);
    }
  });

  it('emits no data field the real restore envelope forbids', () => {
    for (const key of restoreGolden.forbiddenDataKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(data, key),
        `mock apply envelope emits data.${key}, which never appears on a restore envelope`
      ).toBe(false);
    }
  });
});
