/**
 * Binds the E2E mock engine to the real engine's apply envelope.
 *
 * Why this exists: 30 of 31 E2E specs run against `__ENDSTATE_MOCK_ENGINE__`
 * and none spawns a binary, so the mock is the only engine those specs ever
 * see. It was authored from the GUI's own type definitions rather than from
 * engine output, which meant it emitted `items`/`counts` — fields the apply
 * envelope has never had (`counts` belongs to `capture`, `items` to
 * `generations`). Every E2E spec passed while the GUI's reconciliation was
 * inert in production, because the mock supplied exactly the fields the GUI
 * wrongly expected. A suite that mocks the thing under test verifies only that
 * the consumer agrees with itself.
 *
 * The fixture is generated by `tests/contract.test.js` from a real engine run
 * (see `tests/fixtures/apply-envelope.golden.json`), so this test fails the
 * moment the mock and the producer disagree.
 *
 * It pins SHAPE, not values. Statuses depend on what the host already has
 * installed — a developer machine reports `present`, a clean CI runner reports
 * `to_install` — so asserting values here would make the test host-dependent
 * and it would be silenced rather than fixed.
 */
import { describe, it, expect } from 'vitest';
import golden from '../../tests/fixtures/apply-envelope.golden.json';
import restoreGolden from '../../tests/fixtures/restore-envelope.golden.json';
import { scenarioEnvelope } from './mock-engine';

describe('mock engine conforms to the real apply envelope', () => {
  const envelope = scenarioEnvelope('apply_ok_minimal') as Record<string, unknown>;
  const data = envelope.data as Record<string, unknown>;

  it('emits every data field the real engine emits', () => {
    for (const key of golden.dataKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(data, key),
        `mock apply envelope is missing data.${key}, which the real engine emits`
      ).toBe(true);
    }
  });

  it('emits no data field the real engine does not emit', () => {
    for (const key of golden.forbiddenDataKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(data, key),
        `mock apply envelope emits data.${key}, which belongs to a different command ` +
          `and never appears on an apply envelope — a consumer reading it fails silently`
      ).toBe(false);
    }
  });

  it('emits the real envelope wrapper fields', () => {
    for (const key of golden.envelopeKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(envelope, key),
        `mock envelope is missing ${key}`
      ).toBe(true);
    }
  });

  it('emits actions whose items carry the real action fields', () => {
    const actions = data.actions as Array<Record<string, unknown>>;
    expect(Array.isArray(actions)).toBe(true);
    expect(actions.length).toBeGreaterThan(0);

    // `name` and `driver` matter most: the GUI falls back to the raw package
    // ref when `name` is absent, which is what made a never-installed app show
    // as "Warp.Warp" beside friendly-named rows.
    for (const key of ['id', 'status', 'name', 'driver']) {
      expect(
        Object.prototype.hasOwnProperty.call(actions[0], key),
        `mock action is missing ${key}`
      ).toBe(true);
    }
  });

  it('emits summary with the real aggregate fields', () => {
    const summary = data.summary as Record<string, unknown>;
    for (const key of golden.summaryKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(summary, key),
        `mock summary is missing ${key}`
      ).toBe(true);
    }
  });

  it('emits restoreModulesAvailable entries with entryCount', () => {
    const modules = data.restoreModulesAvailable as Array<Record<string, unknown>>;
    expect(Array.isArray(modules)).toBe(true);
    expect(modules.length).toBeGreaterThan(0);

    for (const key of golden.restoreModuleKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(modules[0], key),
        `mock restoreModulesAvailable entry is missing ${key}`
      ).toBe(true);
    }
  });

  it('exposes dryRun so consumers can distinguish a preview from a real apply', () => {
    expect(typeof data.dryRun).toBe('boolean');
  });
});

/**
 * Binds the mock's restore-bearing scenario to the RESTORE golden
 * (tests/fixtures/restore-envelope.golden.json), regenerated by
 * tests/contract.test.js from a real `apply --enable-restore` run.
 *
 * The apply-golden block above checks restoreModulesAvailable[0] once. This
 * block is stricter on the axis the restore lane exists to protect: EVERY entry
 * must carry every key the real engine emits, and every entryCount must be a
 * positive integer — the engine omits a module with no resolved entries rather
 * than reporting it empty, so membership and count cannot disagree. The mock
 * derives entryCount from a single source list for exactly that reason.
 */
describe('mock engine conforms to the real restore envelope', () => {
  const envelope = scenarioEnvelope('apply_ok_minimal') as Record<string, unknown>;
  const data = envelope.data as Record<string, unknown>;
  const modules = data.restoreModulesAvailable as Array<Record<string, unknown>>;

  it('carries a scoped restoreModulesAvailable list', () => {
    expect(Array.isArray(modules)).toBe(true);
    expect(modules.length).toBeGreaterThan(0);
  });

  it('gives every restore module entry the real engine-authored keys', () => {
    for (const module of modules) {
      for (const key of restoreGolden.restoreModuleKeys) {
        expect(
          Object.prototype.hasOwnProperty.call(module, key),
          `mock restoreModulesAvailable entry ${JSON.stringify(module.id)} is missing ${key}, ` +
            `which the real engine emits`
        ).toBe(true);
      }
    }
  });

  it('reports a positive integer entryCount on every entry (membership cannot disagree with count)', () => {
    for (const module of modules) {
      expect(
        Number.isInteger(module.entryCount) && (module.entryCount as number) > 0,
        `mock restoreModulesAvailable entry ${JSON.stringify(module.id)} has a non-positive ` +
          `or non-integer entryCount ${JSON.stringify(module.entryCount)}`
      ).toBe(true);
    }
  });

  it('emits every data field the real restore envelope emits', () => {
    for (const key of restoreGolden.dataKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(data, key),
        `mock apply envelope is missing data.${key}, which the real restore envelope emits`
      ).toBe(true);
    }
  });

  it('emits no data field the real restore envelope forbids', () => {
    for (const key of restoreGolden.forbiddenDataKeys) {
      expect(
        Object.prototype.hasOwnProperty.call(data, key),
        `mock apply envelope emits data.${key}, which never appears on a restore envelope`
      ).toBe(false);
    }
  });
});
